services:
  gateway-service:
    build:
      context: ..
      dockerfile: server/gateway-service/Dockerfile
    container_name: gateway-service
    env_file:
      - ./gateway-service/.env
    ports:
      - "8080:8080"
    networks:
      - app-network

  user-service:
    build:
      context: ..
      dockerfile: server/user-service/Dockerfile
    container_name: user-service
    env_file:
      - ./user-service/.env
    ports:
      - "8083:8083"
    networks:
      - app-network

  auth-service:
    build:
      context: ..
      dockerfile: server/auth-service/Dockerfile
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "8082:8082"
    depends_on:
      - user-service
    networks:
      - app-network
  
  mail-service:
    build:
      context: ..
      dockerfile: server/mail-service/Dockerfile
    container_name: mail-service
    env_file:
      - ./mail-service/.env
    ports:
      - "8086:8086"
    networks:
      - app-network

  cv-service:
    build:
      context: ..
      dockerfile: server/cv-service/Dockerfile
    container_name: cv-service
    env_file:
      - ./cv-service/.env
    ports:
      - "8084:8084"
    depends_on:
      user-service:
        condition: service_started
    networks:
      - app-network

  ai-service:
    build:
      context: ..
      dockerfile: server/ai-service/Dockerfile
    container_name: ai-service
    env_file:
      - ./ai-service/.env
    ports:
      - "8085:8085"
    depends_on:
      cv-service:
        condition: service_started
    networks:
      - app-network

  stats-service:
    build:
      context: ..
      dockerfile: server/stats-service/Dockerfile
    container_name: stats-service
    env_file:
      - ./stats-service/.env
    ports:
      - "8087:8087"
    depends_on:
      user-service:
        condition: service_started
      cv-service:
        condition: service_started
    networks:
      - app-network

volumes:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge