apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jobready

bases:
  - ../../base

patchesStrategicMerge:
  - replica-patch.yaml
  - resources-patch.yaml

commonLabels:
  environment: prod
