apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jobready

resources:
  - namespace.yaml
  - gateway-deployment.yaml
  - auth-deployment.yaml
  - user-deployment.yaml
  - cv-deployment.yaml
  - ai-deployment.yaml
  - mail-deployment.yaml
  - stats-deployment.yaml
  - ../configmaps/gateway-configmap.yaml
  - ../configmaps/auth-configmap.yaml
  - ../configmaps/user-configmap.yaml
  - ../configmaps/cv-configmap.yaml
  - ../configmaps/ai-configmap.yaml
  - ../configmaps/mail-configmap.yaml
  - ../configmaps/stats-configmap.yaml

commonLabels:
  app.kubernetes.io/part-of: jobready
